empresa/posts/empresa/urls.py
from django.contrib import admin
from django.urls import include, path




urlpatterns = [
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

empresa/posts/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
        path('',views.IndexView.as_view(),name='index'),
        path('<int:pk>/',views.DetailView.as_view(),name='detail'),
        path('register/', views.register_consortium, name='register'),
        path('registerClient/', views.register_client, name='registerClient'),
]

empresa/posts/posts/models.py
from django.db import models

class Persona(models.Model):
    codigo = models.CharField('Código',unique=True, max_length=8,default="")
    dni = models.CharField('DNI',unique=True, max_length=8)
    nombre = models.CharField('Nombre',max_length=100)
    apellido = models.CharField('Apellido',max_length=100)
    cargo = models.CharField('Cargo',max_length=100)
    email = models.EmailField('Email')
    fecha_nacimiento = models.DateField('Fecha de Nacimiento')
    fecha_inicio = models.DateField('Fecha de Inicio')
    fecha_fin = models.DateField('Fecha de Fin',null=True)
    vigente = models.BooleanField('Vigente',default=False,blank=True)
    telefono = models.CharField('Número de celular', max_length=30)
    class Meta:
        abstract = True
    def __str__(self):
        return self.nombre + " " + self.apellido


class Proyecto(models.Model):
    cod_proyecto = models.CharField('Código de Proyecto',max_length=20,unique=True)
    cod_snip = models.CharField('Código Snip',max_length=20,default="",unique=True)
    denominacion = models.TextField('Denominación')
    denominacion_corta = models.TextField('Denominación Corta')
    nivel = models.CharField('Nivel',max_length=30)
    funcion = models.CharField('Funcion',max_length=30)
    fase = models.CharField('Fase',max_length=50)
    estado = models.CharField('Estado',max_length=100)
    taxonomia = models.CharField('Taxonomía',max_length=100)
    situacion = models.CharField('Situación',max_length=100)
    fecha_estado = models.DateField('Fecha de Estado')
    fecha_registro = models.DateField('Fecha de Registro')
    activo = models.BooleanField('Activo',default=False,blank=True)
    def __str__(self):
        return self.denominacion_corta

class Personal_Cliente(Persona):
    comentario = models.TextField('Comentario')
    proyecto_id = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    def __str__(self):
        return super(Personal_Cliente, self).__str__()

class Consorcio(models.Model):
    nombre = models.CharField('Nombre del Consorcio',max_length=100)
    proyecto_id = models.OneToOneField(Proyecto, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

class Personal_Consorcio(Persona):
    jefe = models.BooleanField('Jefe',default=False,blank=True)
    costo = models.FloatField('Costo',default=0)
    consorcio_id = models.ForeignKey(Consorcio, on_delete=models.CASCADE)
    def __str__(self):
        return super(Personal_Consorcio, self).__str__()

empresa/posts/posts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic

from .models import Proyecto, Personal_Cliente
from .models import Consorcio, Personal_Consorcio

from django.contrib.auth.models import User



def register_consortium(request):
    if request.method == 'POST':
        if request.POST.get('guardar', '') == 'guardar':

            profile = Personal_Consorcio()
            profile.codigo = request.POST['codigo']
            profile.dni = request.POST['dni']
            profile.nombre = request.POST['nombre']
            profile.apellido = request.POST['apellido']
            profile.cargo = request.POST['cargo']
            profile.email = request.POST['email']
            profile.fecha_nacimiento = request.POST['fecha_nacimiento']
            profile.fecha_inicio = request.POST['fecha_inicio']
            profile.fecha_fin = request.POST['fecha_fin']
            profile.jefe = request.POST.get('jefe', '') == 'on'
            profile.vigente = request.POST.get('vigente', '') == 'on'
            profile.telefono = request.POST['telefono'] 
            profile.costo = request.POST['costo']
            proyecto = Proyecto.objects.get(pk=request.POST['consorcio_id'])
            profile.consorcio_id = proyecto.consorcio

            profile.save()
            return render(request, 'posts/detail.html')

        elif request.POST.get('eliminar', '')=='eliminar':

            Personal_Consorcio.objects.filter(codigo=request.POST['codigo']).delete()
            return render(request, 'posts/detail.html')
        
        elif request.POST.get('actualizar', '') =='actualizar':

            profile = Personal_Consorcio.objects.get(codigo=request.POST['codigo'])

            profile.codigo = request.POST['codigo']
            profile.dni = request.POST['dni']
            profile.nombre = request.POST['nombre']
            profile.apellido = request.POST['apellido']
            profile.cargo = request.POST['cargo']
            profile.email = request.POST['email']
            profile.fecha_nacimiento = request.POST['fecha_nacimiento']
            profile.fecha_inicio = request.POST['fecha_inicio']
            profile.fecha_fin = request.POST['fecha_fin']
            profile.jefe = request.POST.get('jefe', '') == 'on'
            profile.vigente = request.POST.get('vigente', '') == 'on'
            profile.telefono = request.POST['telefono'] 
            profile.costo = request.POST['costo']
            proyecto = Proyecto.objects.get(pk=request.POST['consorcio_id'])
            profile.consorcio_id = proyecto.consorcio


            profile.save()
            return render(request, 'posts/detail.html')

    return render(request, 'posts/register.html')

def register_client(request):
    if request.method == 'POST':
        if request.POST.get('guardar', '') == 'guardar':

            profile = Personal_Cliente()
            profile.codigo = request.POST['codigo']
            profile.dni = request.POST['dni']
            profile.nombre = request.POST['nombre']
            profile.apellido = request.POST['apellido']
            profile.cargo = request.POST['cargo']
            profile.email = request.POST['email']
            profile.fecha_nacimiento = request.POST['fecha_nacimiento']
            profile.fecha_inicio = request.POST['fecha_inicio']
            profile.fecha_fin = request.POST['fecha_fin']
            profile.vigente = request.POST.get('vigente', '') == 'on'
            profile.telefono = request.POST['telefono'] 
            profile.comentario = request.POST['comentario']
            proyectoo = Proyecto.objects.get(pk=request.POST['proyecto_id'])
            profile.proyecto_id = proyectoo

            profile.save()
            return render(request, 'posts/detail.html')

        elif request.POST.get('eliminar', '') =='eliminar':

            Personal_Cliente.objects.filter(codigo=request.POST['codigo']).delete()
            return render(request, 'posts/detail.html')

        elif request.POST.get('actualizar', '') =='actualizar':

            profile = Personal_Cliente.objects.get(codigo=request.POST['codigo'])

            profile.codigo = request.POST['codigo']
            profile.dni = request.POST['dni']
            profile.nombre = request.POST['nombre']
            profile.apellido = request.POST['apellido']
            profile.cargo = request.POST['cargo']
            profile.email = request.POST['email']
            profile.fecha_nacimiento = request.POST['fecha_nacimiento']
            profile.fecha_inicio = request.POST['fecha_inicio']
            profile.fecha_fin = request.POST['fecha_fin']
            profile.vigente = request.POST.get('vigente', '') == 'on'
            profile.telefono = request.POST['telefono'] 
            profile.comentario = request.POST['comentario']
            proyectoo = Proyecto.objects.get(pk=request.POST['proyecto_id'])
            profile.proyecto_id = proyectoo


            profile.save()
            return render(request, 'posts/detail.html')


    return render(request, 'posts/register_client.html')



class IndexView(generic.ListView):
    template_name  = 'posts/index.html'
    context_object_name = 'projects'
    def get_queryset(self):
        """Retorna todos los proyectos registrados hasta ahora"""
        return Proyecto.objects.all()

class DetailView(generic.DetailView):
    model = Proyecto
    template_name = 'posts/detail.html'

empresa/posts/posts/templates/posts/detail.html
<!doctype html>
<html lang="es">
<html>
	<head>
        <title>Index</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no,initial-scale=1.0">
        <!--Bootstrap-->
      <link rel="stylesheet" href="../../static/posts/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="../../static/posts/bootstrap-grid.min.css" type="text/css">
      <link rel="stylesheet" href="../../static/posts/bootstrap-reboot.min.css" type="text/css">
      <!--Css Propio-->
      <link rel="stylesheet" href="../../static/posts/estilos.css">
      <!--Iconos-->
      <script src="https://kit.fontawesome.com/01f86331e9.js" crossorigin="anonymous"></script>
      <!--DataTables-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
      <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
	</head>
	<body>
        <main class="container-fluid">
            
            <!-- Datos generales del proyecto -->
            <div class="card mt-3 mb-3 bg-light">
                <!-- Muestra de datos -->  
                <div class=" card-body ">    
                    <h2 class="text-center card-title mb-4 font-weight-bold">{{ proyecto }}</h2>
                </div>
            </div><!-- Fin de tarjeta de Datos generales del proyecto -->
            
            <div class="card shadow mb-4">
                <div class=" card-body ">
                   <a class="btn btn-primary" href="{% url 'posts:index' %}">Volver</a>
                    <h3 class="text-center">{{proyecto.consorcio}}</h3>
                    <h5 class="card-title mb-4 font-weight-bold">Personal del Consorcio</h5>
                    <!-- Muestra la tabla Personal del Consorcio -->
                    <div class="table-responsive mb-5">
                        <table id="TablaPersoConsorcio" class=" table table-sm table-bordered table-hover"> <!--font-weight-light-->
                            <thead>
                                <tr>
                                    <th scope="col">N°</th>
                                    <th scope="col">Cod.</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Cargo</th>
                                    <th scope="col">Teléfono</th>
                                    <th scope="col">Correo</th>
                                    <th scope="col">F. Ini.</th>
                                    <th scope="col">F. Fin</th>
                                    <th scope="col">Jefe</th>
                                    <th scope="col">Costo (S/)</th>
                                    <th scope="col">Vigente</th>
                                </tr>
                            </thead>        
                            <tbody class="" id ="espacioMCConsorcio">
                             {% for persona in proyecto.consorcio.personal_consorcio_set.all %}
                                <tr>
                                   <td>{{persona.id}}</td>
                                   <td>{{persona.codigo}}</td>
                                   <td>{{persona.nombre}}</td>
                                   <td>{{persona.cargo}}</td>
                                   <td>{{persona.telefono}}</td>
                                   <td>{{persona.email}}</td>
                                   <td>{{persona.fecha_inicio}}</td>
                                   <td>{{persona.fecha_fin}}</td>
                                   <td>{{persona.jefe}}</td>
                                   <td>{{persona.costo}}</td>
                                   <td>{{persona.vigente}}</td>
                                </tr>
                             {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <h5 class="card-title mb-4 mt-5 font-weight-bold">Especialistas del Cliente</h5>
                    <!-- Muestra la tabla Especialistas del Cliente -->       
                    <div class="table-responsive"> 
                        <table id="TablaCliente" class="table table-sm table-bordered table-hover"> <!--font-weight-light-->
                            <thead >
                                <tr>
                                    <th scope="col">N°</th>
                                    <th scope="col">Cod.</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Cargo</th>
                                    <th scope="col">Teléfono</th>
                                    <th scope="col">Correo</th>
                                    <th scope="col">F. Ini.</th>
                                    <th scope="col">F. Fin</th>
                                    <th scope="col">Comentario</th>
                                    <th scope="col">Vigente</th>
                                </tr>
                            </thead>
                            <tbody class="" id ="espacioMCCliente" >
                             {% for persona in proyecto.personal_cliente_set.all %}
                                <tr>
                                   <td>{{persona.id}}</td>
                                   <td>{{persona.codigo}}</td>
                                   <td>{{persona.nombre}}</td>
                                   <td>{{persona.cargo}}</td>
                                   <td>{{persona.telefono}}</td>
                                   <td>{{persona.email}}</td>
                                   <td>{{persona.fecha_inicio}}</td>
                                   <td>{{persona.fecha_fin}}</td>
                                   <td>{{persona.comentario}}</td>
                                   <td>{{persona.vigente}}</td>
                                </tr>
                             {% endfor %}
                            </tbody>
                        </table>
                    </div><!-- Fin de Tabla Especialistas del Cliente -->
                </div>
            </div>
        </main>

        
        <!--- Popup Ver Personal del Consorcio -->
        <div class="modal fade" id="ver-personal-consorcio">
            <div class="modal-dialog modal-dialog-centered tamaño">  
                <div class="modal-content">
                    <div class="modal-header justify-content-center">
                        <h5 class="modal-title">Detalles Personal del Consorcio</h5>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-3">
                              <label>Código</label>
                              <p id="codigoPer-ver"></p>
                            </div>
                            <div class="col-md-9">
                              <label>Apellidos y Nombres</label>
                              <p id="nombrePer-ver"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <label>Teléfono</label>
                                <p id="telefonoPer-ver"></p>
                            </div>
                            <div class="col-md-9">
                                <label>Correo</label>
                                <p id="correoPer-ver"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7">
                                <label>Cargo</label>
                                <p id="cargoPer-ver"></p>
                            </div>
                            <div class="col-md-5">
                                <label>Fecha Inicio</label>
                                <p id="fecha-iniPer-ver"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7">
                                <label>Costo</label>
                                <p id="costoPer-ver"></p>
                            </div>
                            <!--div class="col-md-4">
                                <label>Esp - Prov</label>
                                <p id="esp-provPer-ver"></p>
                            </div-->
                            <div class="col-md-5">
                                <label>Fecha Fin</label>
                                <p id="fecha-finPer-ver"></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="jefeProy-ver" disabled>
                                <label class="form-check-label">
                                    Jefe de Proyecto
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                                <input checked class="form-check-input" type="checkbox" value="" id="vigentePer-ver" disabled>
                                <label class="form-check-label" for="vigentePer">
                                    Vigente
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Boton desplazamiento hacai arriba -->
        <boton type="button"><i id="scroll-hacia-arriba" class="scroll-hacia-arriba fas fa-angle-up rounded" ></i></boton>

        <!-- Menu Contextual Tabla Personal del Consorcio -->
        <div id="menuContextualConsorcio" class="dropdown-menu">
            <boton id="botonVerConsor" class ="dropdown-item" type="button" data-toggle="modal" data-target="#ver-personal-consorcio">Ver</boton>
            <boton id="botonAgregarConsorcio" class ="dropdown-item" type="button" data-toggle="modal" data-target="#agregar-personal-consorcio">Nuevo</boton>
            <boton id="botonModificarConsorcio" class ="dropdown-item" type="button" data-toggle="modal" data-target="#agregar-personal-consorcio">Editar</boton>
            <boton id="botonEliminarConsorcio" class="dropdown-item" type="button" data-toggle="modal" data-target="#modal-eliminar">Eliminar</boton>
        </div>

        <!-- Menu Contextual Tabla Especialistas del Cliente -->
        <div id="menuContextualCliente" class="dropdown-menu">
            <boton id="botonVerCliente" class ="dropdown-item" type="button" data-toggle="modal" data-target="#ver-especialistas-cliente">Ver</boton>
            <boton id="botonAgregarCliente" class ="dropdown-item" type="button" data-toggle="modal" data-target="#agregar-especialistas-cliente">Nuevo</boton>
            <boton id="botonModificarCliente" class ="dropdown-item" type="button" data-toggle="modal" data-target="#agregar-especialistas-cliente">Editar</boton>
            <boton id="botonEliminarCliente" class="dropdown-item" type="button" data-toggle="modal" data-target="#modal-eliminar">Eliminar</boton>
        </div>
        
        <script src="../../static/posts/jquery.js"></script>
        <script src="../../static/posts/bootstrap.bundle.min.js"></script>
        <script src="../../static/posts/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
        <script src="../../static/posts/script.js"></script>
    </body>
</html>

empresa/posts/posts/templates/posts/index.html
<!doctype html>
<html lang="es">
<html>
	<head>
        <title>Index</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no,initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0">
        <!--Bootstrap-->
        <link rel="stylesheet" href="../../static/posts/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="../../static/posts/bootstrap-grid.min.css" type="text/css">
        <link rel="stylesheet" href="../../static/posts/bootstrap-reboot.min.css" type="text/css">
        <!--Css Propio-->
        <link rel="stylesheet" href="../../static/posts/estilos.css">
        <!--Iconos-->
        <script src="https://kit.fontawesome.com/01f86331e9.js" crossorigin="anonymous"></script>
        <!--DataTables-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
	</head>
	<body>
        <main class="container-fluid">
            <!-- Datos generales del proyecto -->
            <div class="card mt-3 mb-3 bg-light">
                <!-- Muestra de datos -->  
                <div class=" card-body">        
                    <h3 class="card-title mb-4 font-weight-bold text-center">Proyectos</h3>
                    <div class="table-responsive">
                        <table id="TablaDatosConsorcio" class="table table-sm table-bordered table-striped table-hover"> <!--class="table table-sm table-bordered table-striped"-->
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Denominación corta</th>
                                    <th>Consorcio</th>
                                    <th>Fase</th>
                                    <th>Nivel</th>
                                    <th>Funcion</th>
                                    <th>Taxonomía</th>
                                    <th>Estado</th>
                                </tr>
                            </thead>
                            <tbody>
                               {% if projects %}
                                 {% for project in projects %}
                                 <tr>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.cod_proyecto }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.denominacion_corta }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.consorcio }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.fase }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.nivel }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.funcion }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.taxonomia }}</a></td>
                                    <td><a class = "text-reset" href="{% url 'posts:detail' project.id %}">{{ project.estado }}</a></td>
                                 </tr>
                                 {% endfor %}
                               {% else %}
                                 <p>No hay proyectos disponibles</p>
                               {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div><!-- Fin de tarjeta de Datos generales del proyecto -->
            <script src="../../static/posts/jquery.js"></script>
            <script src="../../static/posts/bootstrap.bundle.min.js"></script>
            <script src="../../static/posts/bootstrap.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
            <script src="../../static/posts/script.js"></script>
    </body>
</html>

empresa/posts/posts/templates/posts/register.html
<!doctype html>
<html lang="es">
<html>
	<head>
        <title>Registrar</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no,initial-scale=1.0">
        <!--Bootstrap-->
        <link rel="stylesheet" href="../../static/posts/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="../../static/posts/bootstrap-grid.min.css" type="text/css">
        <link rel="stylesheet" href="../../static/posts/bootstrap-reboot.min.css" type="text/css">
        <!--Css Propio-->
        <link rel="stylesheet" href="../../static/posts/estilos.css">
        <!--Iconos-->
        <script src="https://kit.fontawesome.com/01f86331e9.js" crossorigin="anonymous"></script>
        <!--DataTables-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
	</head>
	<body>
        <div class="modal-body">
            <!-- Forma Ingresar personal del consorcio -->
            {% block container %}
            <form id="forma-personal-consorcio" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-3">
                      <label for="codigo">Código</label>
                      <input type="text" class="form-control" id="codigo" name="codigo">
                    </div>
                    <div class="form-group col-md-9">
                      <label for="nombre">Nombres</label>
                      <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                    <div class="form-group col-md-9">
                        <label for="apellido">Apellidos</label>
                        <input type="text" class="form-control" id="apellido" name="apellido">
                    </div>
                    <div class="form-group col-md-9">
                        <label for="dni">DNI</label>
                        <input type="text" class="form-control" id="dni" name="dni">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="telefono">Teléfono</label>
                        <input type="text" class="form-control" id="telefono" name="telefono">
                    </div>
                    <div class="form-group col-md-9">
                        <label for="email">Correo</label>
                        <input type="email" class="form-control" id="email" name="email">
                    </div>
                    <div class="form-group col-md-5">
                        <label for="fecha_nacimiento">Fecha Nacimiento</label>
                        <input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-7">
                        <label for="cargo">Cargo</label>
                        <input type="text" class="form-control" id="cargo" name="cargo">
                    </div>
                    <div class="form-group col-md-5">
                        <label for="fecha_inicio">Fecha Inicio</label>
                        <input type="date" class="form-control" id="fecha_inicio" name="fecha_inicio"> <!--value="2017-02-04"-->
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-7">
                        <label for="costo">Costo</label>
                        <input type="number" class="form-control" id="costo" name="costo">
                    </div>
                    <!--div class="col-md-4">
                        <label for="esp-prov">Esp - Prov</label>
                        <select class="custom-select" id="esp-provPer">
                            <option selected disabled value="">Elija...</option>
                            <option value="Especialista">Especialista </option>
                            <option value="Proveedor">Proveedor</option>
                        </select>
                    </div-->
                    <div class="form-group col-md-5">
                        <label for="fecha_fin">Fecha Fin</label>
                        <input type="date" class="form-control" id="fecha_fin" name="fecha_fin">
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                      <input  class="form-check-input" type="checkbox"  id="jefe" name="jefe">
                      <label class="form-check-label" for="jefe">
                        Jefe de Proyecto
                      </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                      <input  class="form-check-input" type="checkbox"   id="vigente" name="vigente">
                      <label class="form-check-label" for="vigente">
                        Vigente
                      </label>
                    </div>
                </div>
                <div class="form-group col-md-9">
                    <label for="consorcio_id">Codigo Consorcio</label>
                    <input type="number" class="form-control" id="consorcio_id" name="consorcio_id">
                </div>
                <div class="modal-footer justify-content-around">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary" form="forma-especialistas-cliente" type="submit" name="guardar" value="guardar">Guardar</button>
                    <button type="submit" class="btn btn-primary" form="forma-especialistas-cliente" type="submit" name="eliminar" value="eliminar">Eliminar</button>
                </div>
            </form>
            {% endblock %} 
        </div>

        <script src="../../static/posts/jquery.js"></script>
        <script src="../../static/posts/bootstrap.bundle.min.js"></script>
        <script src="../../static/posts/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
        <script src="../../static/posts/script.js"></script>
    </body>
</html>

        
        